AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  random_word

  Serverless api for student at Ensai

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize : 512

Resources:
  WordGeneratorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: app.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        RandomWord:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /word/{proxy+}
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RandomWorddApi:
    Description: "API Gateway endpoint URL for Prod stage for Word generator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/randomword"
  RandomWordFunction:
    Description: "Word generator Lambda Function ARN"
    Value: !GetAtt WordGeneratorFunction.Arn
  RandomWordFunctionIamRole:
    Description: "Implicit IAM Role created for Word generator function"
    Value: !GetAtt WordGeneratorFunctionRole.Arn
