words={
    "fr": {
        4:["FOUR", "GROS", "IODA", "CRUE", "HUIT"],
        5:["AIGLE", "DEMON", "ETAPE", "MALLE", "ULULA"],
        6:["ABATTE", "BAREME", "FAUNES", "LOTION", "RAMENT"],
        7:["ACCOUER", "CHAIRES", "DELECTE", "LOCATIF", "VOYELLE"],
        8:["ALMANACH", "CAPITOLE", "DEGUSTEZ", "EPOUMONE", "MIXTURES"],
        9:["DEJOUAMES", "FATALISME", "MASTARDES", "PAVESANES", "REBIFFIEZ"],
        10:["CAMBRIENNE", "CONTRARIEE", "GLANDERAIS", "PITUITEREZ", "ZAPPERIONS"],
        11:["VOUVOIERIEZ", "REAPPRENNES", "DROGUERIONS", "COPROPHAGIE", "BLANQUISTES"],
        12:["BYZANTINISME", "CONTRATTAQUA", "ENCHIFRENENT", "MARSOUINASSE", "REMAQUILLIEZ"]
    },
    "en":{
        4:["JAZZ", "ZIFF", "JOWL", "JERK", "QUIM"],
        5:["PIZZA", "JUMPY", "KHAZI", "FUZED", "KANZU"],
        6:["ABOLLA", "MIZZLE", "JIMPLY", "BUZUKI", "QUACKY"],
        7:["BUZZCUT", "HUZZAHS", "JUJUBES", "JUMPOFF", "FUZZBOX"],
        8:["UNMUZZLE", "JIPIJAPA", "POZZOLAN", "HIGHJACK", "MAXIMIZE"],
        9:["QUIZZICAL", "SCUZZBAGS", "CHEAPJACK", "MEZZALUNA", "PODZOLIZE"],
        10:["RAZZMATAZZ", "BUZZWORTHY", "BLACKJACKS", "POZZOLANIC", "BLIZZARDLY"],
        11:["BUZZPHRASES", "PUZZLEMENTS", "KOLKHOZNIKS", "KICKBOXING", "OUTDAZZLING"],
        12:["BEDAZZLEMENT", "JOURNALIZING", "MUZZLELOADER", "QUICKSTEPPED", "POLYGAMINZING"]
    },
    "es":{
        4:["ABRA", "CAPI", "DUOS", "ECHO", "IDEO"],
        5:["CAJOS", "JADEE", "YERME", "PAJAR", "RALLA"],
        6:["SACHAR", "XECUDO", "LACIOS", "IDALIO", "GABINA"],
        7:["BACARAY", "TABLIZO", "QUEJURA", "HACANES", "NACRITA"],
        8:["VACUNADO", "ZABULLIR", "JABONOSA", "MACARROS", "PACTABAN"],
        9:["ABADENGOS", "BACHATERA", "HABLARIAS", "MACEARIAS", "OBISPASTE"],
        10:["YACERIAMOS", "IDIOLECTOS", "LABRASTEIS", "GALANTEARA", "DACTILICAS"],
        11:["UBICACIONES", "ECOLOGISTAS", "FACHENDEASE", "QUADRIVIUMS", "TABACALERAS"],
        12:["YUXTAPONDRAN", "JABONEABAMOS", "DEAMBULARAIS", "SACALOSUCHIL", "CABECIBLANCO"]
    }
}